name: finger_print_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.3
  local_auth: ^2.1.6 # for fingerprint access
  crypto: ^3.0.3 # for hashing
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
